const data=[
    {
        id:'1',
        title: "Only on Netflix",
        innerArray:[
                {
                  id:'1',
                  url: require('.././assets/mindhunter.jpg'),
                  year: '2019',
                  age: '16+',
                  time: '2 seasons',
                  info: 'Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.',
                  cast: ' Jonathan Groff, Holt McCallany, Anna Torv',
                  director: 'Joe Penhall',
                },
                {
                    id:'2',
                    url: require('.././assets/ray.jpg'),
                    year: '2021',
                    age: '16+',
                    time: '3h 20m',
                    info: 'From a satire to a psychological thriller, four short stories from celebrated auteur and writer Satyajit Ray are adapted for the screen in this series.',
                    cast: ' Manoj Bajpai, Gajraj Rao, Kay Kay Menon',
                    director: 'Joe Penhall',
                },
                {
                    id:'3',
                    url: require('.././assets/suits.jpg'),
                    year: '2019',
                    age: '16+',
                    time: '10h 20m',
                    info: 'When he impresses a big lawyer with his razor-shaped mind, a college dropout scores a coveted associate job, even though he has no legal credentials.',
                    cast: ' Gabriel Macht, Patrick J. Adams, Gina Torres',
                    director: ' Aaron Korsh',
                },
                 {
                    id:'4',
                    url: require('.././assets/undercover.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'5',
                    url: require('.././assets/she.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'6',
                    url: require('.././assets/lucifer.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'7',
                    url: require('.././assets/dark.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'8',
                    url: require('.././assets/betaal.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                }]
    },

    {
        id:'2',
        title: "Top 10 in India Today",
         innerArray:[
                {
                  id:'1',
                  url: require('.././assets/mindhunter.jpg'),
                  year: '2019',
                  age: '16+',
                  time: '2 seasons',
                  info: 'Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.',
                  cast: ' Jonathan Groff, Holt McCallany, Anna Torv',
                  director: 'Joe Penhall',
                },
                {
                    id:'2',
                    url: require('.././assets/ray.jpg'),
                    year: '2021',
                    age: '16+',
                    time: '3h 20m',
                    info: 'From a satire to a psychological thriller, four short stories from celebrated auteur and writer Satyajit Ray are adapted for the screen in this series.',
                    cast: ' Manoj Bajpai, Gajraj Rao, Kay Kay Menon',
                    director: 'Joe Penhall',
                },
                {
                    id:'3',
                    url: require('.././assets/suits.jpg'),
                    year: '2019',
                    age: '16+',
                    time: '10h 20m',
                    info: 'When he impresses a big lawyer with his razor-shaped mind, a college dropout scores a coveted associate job, even though he has no legal credentials.',
                    cast: ' Gabriel Macht, Patrick J. Adams, Gina Torres',
                    director: ' Aaron Korsh',
                },
                 {
                    id:'4',
                    url: require('.././assets/undercover.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'5',
                    url: require('.././assets/she.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'6',
                    url: require('.././assets/lucifer.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'7',
                    url: require('.././assets/dark.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'8',
                    url: require('.././assets/betaal.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                }]
    },

    {
        id:'3',
        title: "Trending Now",
         innerArray:[
                {
                  id:'1',
                  url: require('.././assets/mindhunter.jpg'),
                  year: '2019',
                  age: '16+',
                  time: '2 seasons',
                  info: 'Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.',
                  cast: ' Jonathan Groff, Holt McCallany, Anna Torv',
                  director: 'Joe Penhall',
                },
                {
                    id:'2',
                    url: require('.././assets/ray.jpg'),
                    year: '2021',
                    age: '16+',
                    time: '3h 20m',
                    info: 'From a satire to a psychological thriller, four short stories from celebrated auteur and writer Satyajit Ray are adapted for the screen in this series.',
                    cast: ' Manoj Bajpai, Gajraj Rao, Kay Kay Menon',
                    director: 'Joe Penhall',
                },
                {
                    id:'3',
                    url: require('.././assets/suits.jpg'),
                    year: '2019',
                    age: '16+',
                    time: '10h 20m',
                    info: 'When he impresses a big lawyer with his razor-shaped mind, a college dropout scores a coveted associate job, even though he has no legal credentials.',
                    cast: ' Gabriel Macht, Patrick J. Adams, Gina Torres',
                    director: ' Aaron Korsh',
                },
                 {
                    id:'4',
                    url: require('.././assets/undercover.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'5',
                    url: require('.././assets/she.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'6',
                    url: require('.././assets/lucifer.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'7',
                    url: require('.././assets/dark.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'8',
                    url: require('.././assets/betaal.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                }]
    },

    {
        id:'4',
        title: "Continue Watching for User",
         innerArray:[
                {
                  id:'1',
                  url: require('.././assets/mindhunter.jpg'),
                  year: '2019',
                  age: '16+',
                  time: '2 seasons',
                  info: 'Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.',
                  cast: ' Jonathan Groff, Holt McCallany, Anna Torv',
                  director: 'Joe Penhall',
                },
                {
                    id:'2',
                    url: require('.././assets/ray.jpg'),
                    year: '2021',
                    age: '16+',
                    time: '3h 20m',
                    info: 'From a satire to a psychological thriller, four short stories from celebrated auteur and writer Satyajit Ray are adapted for the screen in this series.',
                    cast: ' Manoj Bajpai, Gajraj Rao, Kay Kay Menon',
                    director: 'Joe Penhall',
                },
                {
                    id:'3',
                    url: require('.././assets/suits.jpg'),
                    year: '2019',
                    age: '16+',
                    time: '10h 20m',
                    info: 'When he impresses a big lawyer with his razor-shaped mind, a college dropout scores a coveted associate job, even though he has no legal credentials.',
                    cast: ' Gabriel Macht, Patrick J. Adams, Gina Torres',
                    director: ' Aaron Korsh',
                },
                 {
                    id:'4',
                    url: require('.././assets/undercover.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'5',
                    url: require('.././assets/she.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'6',
                    url: require('.././assets/lucifer.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'7',
                    url: require('.././assets/dark.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'8',
                    url: require('.././assets/betaal.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                }]
    },
    {
        id:'5',
        title: "Watch It Again",
         innerArray:[
                {
                  id:'1',
                  url: require('.././assets/mindhunter.jpg'),
                  year: '2019',
                  age: '16+',
                  time: '2 seasons',
                  info: 'Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.',
                  cast: ' Jonathan Groff, Holt McCallany, Anna Torv',
                  director: 'Joe Penhall',
                },
                {
                    id:'2',
                    url: require('.././assets/ray.jpg'),
                    year: '2021',
                    age: '16+',
                    time: '3h 20m',
                    info: 'From a satire to a psychological thriller, four short stories from celebrated auteur and writer Satyajit Ray are adapted for the screen in this series.',
                    cast: ' Manoj Bajpai, Gajraj Rao, Kay Kay Menon',
                    director: 'Joe Penhall',
                },
                {
                    id:'3',
                    url: require('.././assets/suits.jpg'),
                    year: '2019',
                    age: '16+',
                    time: '10h 20m',
                    info: 'When he impresses a big lawyer with his razor-shaped mind, a college dropout scores a coveted associate job, even though he has no legal credentials.',
                    cast: ' Gabriel Macht, Patrick J. Adams, Gina Torres',
                    director: ' Aaron Korsh',
                },
                 {
                    id:'4',
                    url: require('.././assets/undercover.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'5',
                    url: require('.././assets/she.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'6',
                    url: require('.././assets/lucifer.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'7',
                    url: require('.././assets/dark.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                },
                {
                    id:'8',
                    url: require('.././assets/betaal.jpg'),
                    year: '2016',
                    age: '16+',
                    time: '10h 20m',
                    info: 'A defence lawyer tries to finally uncover the truth of an old miscarriage of justice, while her husband goes to any lengths to conceal the truth about his own past.',
                    cast: ' Sophie Okonedo, Adrian Lester, Dennis Haysbert',
                    director: ' Aaron Korsh',
                }]
    }

];


export default data;